### ISSUE TITLE
[PATTERN] Add a number pattern in C, Pattern41

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#100]
## Task
for the given input n the following pattern should print (n=5 for the below pattern)

### Pattern Image

![41](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/1ecbc184-6867-42d1-8339-90029de8e70c)

### Filename

Pattern41.c

**Comment by abhishek09827** [comment]
pls assign this task to me

**Comment by Vishal21121** [comment]
pr merged #103
