### ISSUE TITLE
[PATTERN] Add a number pattern in Python, Pattern41

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#101]
## Task
for the given input n the following pattern should print (n=5 for the below pattern)

### Pattern Image

![41](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/8593f090-30f0-4985-913a-1646daf95360)

### Filename

Pattern41.py

**Comment by achhayapathak** [comment]
Committed all 4 Pattern41 task, merge them

**Comment by abhishek09827** [comment]
pls assign this task to me

**Comment by Vishal21121** [comment]
pr merged #103
