### ISSUE TITLE
[PATTERN] Add Alphabet pattern in C, Pattern42

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#104]
## Task:
for the given input n the following pattern should print (n=6 for the below pattern):

### Pattern Image

![42](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/14a1cf4b-0aa6-42e1-8009-583aa2cc02cd)

### Filename

Pattern42.c

**Comment by GiuliaBortone** [comment]
Hi there, I would like to contribute to this task. Could you please assign it to me?

**Comment by Vishal21121** [comment]
ok, @GiuliaBortone you can work on this issue.
