### ISSUE TITLE
[PATTERN] Add Alphabet pattern in Java, Pattern42

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#105]
## Task:
for the given input n the following pattern should print (n=6 for the below pattern):

### Pattern Image

![42](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/873f0901-9cdc-420c-9b34-6ad137ad24c2)

### Filename

Pattern42.java

**Comment by abhishek09827** [comment]
Hello , pls assign this task to me

**Comment by Vishal21121** [comment]
ok @abhishek09827 you can work on this issue.

**Comment by Vishal21121** [comment]
pr merged #114
