### ISSUE TITLE
[PATTERN] Add Alphabet pattern in JavaScript, Pattern42

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#107]
## Task:
for the given input n the following pattern should print (n=6 for the below pattern):

### Pattern Image

![42](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/ad410dbc-b418-42e1-95fa-81ed748f4eae)

### Filename

Pattern42.js

**Comment by OkelloSam21** [comment]
Assign this to me

**Comment by Vishal21121** [comment]
ok, @OkelloSam21 you can work on this issue.
