### ISSUE TITLE
[PATTERN] Add Alphabet pattern in Python, Pattern42

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#108]
## Task:
for the given input n the following pattern should print (n=6 for the below pattern):

### Pattern Image

![42](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/717645d9-0585-4cfe-a551-8f026014a4bd)

### Filename

Pattern42.py

**Comment by OkelloSam21** [comment]
assign me this

**Comment by Vishal21121** [comment]
@OkelloSam21 you can work on this issue.

**Comment by OkelloSam21** [comment]
Done

**Comment by Vishal21121** [comment]
@OkelloSam21 but I did not get any pr.

**Comment by Vishal21121** [comment]
pr merged #109
