### ISSUE TITLE
[PATTERN] Add Pascal Triangle pattern in C, Pattern43

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#112]
## Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![43](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/92efbb7c-e014-479d-a30f-80be5feeaca0)

### Filename

Pattern43.c

**Comment by abhishek09827** [comment]
Solved it, pls assign

**Comment by Harshal662** [comment]
Can you please assign it to me. I have code ready.

**Comment by Harshal662** [comment]
Can you please assign it to me. I have code ready.

**Comment by SimranLahrani842** [comment]
> ### Description
> ## Task:
> for the given input n the following pattern should print (n=5 for the below pattern):
> 
> ### Pattern Image
> ![43](https://user-images.githubusercontent.com/89929777/241951217-92efbb7c-e014-479d-a30f-80be5feeaca0.png)
> 
> ### Filename
> Pattern43.c

Assign me this @Vishal21121

**Comment by Vishal21121** [comment]
@Harshal662 It's requested to make a pr only if you are assigned as this helps both the contributor as well as the maintainer.

**Comment by Vishal21121** [comment]
pr merged #124
