### ISSUE TITLE
[PATTERN] Add Pascal Triangle pattern in Java, Pattern43

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#113]
## Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![43](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/d1800b00-0ea6-4e58-9fe7-cd15f70251b1)

### Filename

Pattern43.java

**Comment by abhishek09827** [comment]
Hello , pls assign this task to me

**Comment by Vishal21121** [comment]
@abhishek09827 please solve previously assigned issue before asking for another one.

**Comment by Vishal21121** [comment]
> Hi, can you assign this issue to me?

@RenatBl this issue is already assigned to someone else.

**Comment by Vishal21121** [comment]
> Also, if you don't mind, I would like to do some refactoring In the Pattern.java, Pattern33.java, Pattern_3.java classes, the class name does not match the file name, I could fix this

@RenatBl if you want to work on those issues raise the issue specifying the bug and Pattern. Raise separate issues for the different patterns.

**Comment by RenatBl** [comment]
> > Also, if you don't mind, I would like to do some refactoring In the Pattern.java, Pattern33.java, Pattern_3.java classes, the class name does not match the file name, I could fix this
> 
> @RenatBl if you want to work on those issues raise the issue specifying the bug and Pattern. Raise separate issues for the different patterns.

@Vishal21121 Opened a new issue: https://github.com/Vishal21121/Patterns-different-language/issues/130
Can you assign it to me?

For this issue, I have a ready-made solution, if you allow, I would like to provide it

**Comment by Vishal21121** [comment]
pr merged #122
