### ISSUE TITLE
[PATTERN] Add Eight shape star pattern in JavaScript, Pattern44

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#116]
## Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![44](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/f8800722-81e9-4991-9790-f6e046527921)

### Filename

Pattern44.js

**Comment by akansjain** [comment]
Hey @Vishal21121 ,
Please assign this issue to me.

**Comment by Vishal21121** [comment]
ok ,@akansjain you can work on this issue.
