### ISSUE TITLE
[PATTERN] Add Eight shape star pattern in C, Pattern44

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#117]
## Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![44](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/2e792094-924f-4e91-baba-a083cbc13764)

### Filename

Pattern44.c

**Comment by SimranLahrani842** [comment]
> ### Description
> ## Task:
> for the given input n the following pattern should print (n=5 for the below pattern):
> 
> ### Pattern Image
> ![44](https://user-images.githubusercontent.com/89929777/243034266-2e792094-924f-4e91-baba-a083cbc13764.png)
> 
> ### Filename
> Pattern44.c

Assign me this issue @Vishal21121

**Comment by Vishal21121** [comment]
@SimranLahrani842 someone has already made a pr for this issue.

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 someone has already made a pr for this issue.

Which issue number?
Can u mention it?
