### ISSUE TITLE
[PATTERN] Add Eight shape star pattern in Python, Pattern44

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#118]
## Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![44](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/d4619698-ad6e-4c31-86f6-f7e0d294fd26)

### Filename

Pattern44.py

**Comment by HeatherWatson1** [comment]
Hello can I be assigned this issue?

**Comment by Vishal21121** [comment]
ok, @HeatherWatson1 you can work on this issue.
