### ISSUE TITLE
Add New Shell variant for Existing Pattern

### ISSUE THREAD

**Issue by aneeshd27** [Vishal21121/Patterns-different-language#140]
I want to add shell scripting variant for Pattern24 and Pattern29

**Comment by Vishal21121** [comment]
ok, @aneeshd27 you can work on this issue. If you want to work on another Pattern which is not there in this repo then please fill in all the details for that pattern.

**Comment by aneeshd27** [comment]
[Issue.zip](https://github.com/Vishal21121/Patterns-different-language/files/11712347/Issue.zip)

I have added a Zip file for Pattern24.sh and Pattern29.sh

**Comment by aneeshd27** [comment]
I have added the 2 files in a Zip file

**Comment by Vishal21121** [comment]
@aneeshd27 add the files in the respective folder and then make a pr. Then only I will be able to merge your code.

**Comment by aneeshd27** [comment]
OK

**Comment by Vishal21121** [comment]
> OK

@aneeshd27 why you are closing this issue again and again let it be open.

**Comment by aneeshd27** [comment]
Sorry for the mistake

**Comment by Vishal21121** [comment]
pr merged #141
