### ISSUE TITLE
[Pattern] Add Some pattern in Go

### ISSUE THREAD

**Issue by Mudit-Jxin7** [Vishal21121/Patterns-different-language#150]
### Description

Pattern 38 and Pattern 43 are currently not implemented in Go. However, I'm willing to contribute by writing the code for these patterns in Go.

### Pattern Image

Pattern 43 : 
![image](https://github.com/Vishal21121/Patterns-different-language/assets/97677133/63cf808d-836e-4e4d-acd7-2ed802e9ed1d)

Pattern 38 : 
![image](https://github.com/Vishal21121/Patterns-different-language/assets/97677133/4046bd6e-84ad-4633-b1e5-a3c1fd7d90e6)

**Comment by Vishal21121** [comment]
pr merged #152 #153
