### ISSUE TITLE
[ADD patterns] adding new patterns in java and python

### ISSUE THREAD

**Issue by GauriTr** [Vishal21121/Patterns-different-language#154]
### Description

I am willing to add 2 new patterns in java and i will add them in pythont too.

### Pattern Image

<img width="329" alt="image" src="https://github.com/Vishal21121/Patterns-different-language/assets/129727667/39eec555-f150-4ac8-a74e-0117ef488724">

<img width="307" alt="image" src="https://github.com/Vishal21121/Patterns-different-language/assets/129727667/52cf396d-bfa0-4425-96a3-16dad28911af">

**Comment by Vishal21121** [comment]
ok, @GauriTr you can work on this issue. There are two patterns so name the in the format mentioned in the Announcement and keep each pattern in a different folder.

**Comment by Mudit-Jxin7** [comment]
Hey , I can add the C , JS and  Go code for these two patterns

**Comment by Vishal21121** [comment]
> Hey, I can add the C , JS and Go code for these two patterns

ok, @Mudit-Jxin7 you can contribute to that, but please make separate pr for each Pattern or different languages.

**Comment by Vishal21121** [comment]
pr merged #157
