### ISSUE TITLE
[ADD PATTERN] add a pattern in C language

### ISSUE THREAD

**Issue by 20a31a05e8** [Vishal21121/Patterns-different-language#159]
### Description

I want to add a pattern in C language.

### Pattern Image

![Pattern46](https://github.com/Vishal21121/Patterns-different-language/assets/109792880/77b47013-9199-4410-af60-e6bfb10c811c)

### Filename

Pattern47.C

**Comment by Vishal21121** [comment]
@20a31a05e8 first correct the changes which are requested in pr #145 #146 and issue for Pattern45, and Pattern46 are already done so please changes the pattern number and for everyone's convenience I will make an announcement in the discussion for the Patterns whose issue has been raised, I think it will remove the confusion in raising the issue for others.

**Comment by Vishal21121** [comment]
pr merged #160
