### ISSUE TITLE
[ADD PATTERN] add a pattern in python

### ISSUE THREAD

**Issue by 20a31a05e8** [Vishal21121/Patterns-different-language#162]
### Description

I want to add a pattern in Python

### Pattern Image

![Pattern46](https://github.com/Vishal21121/Patterns-different-language/assets/109792880/36929149-a672-4177-aa1e-604dfca6ff55)

### Filename

Pattern45.py

**Comment by Vishal21121** [comment]
@20a31a05e8 please make changes as mentioned in issue #169 and sorry for the inconvenience.

**Comment by Vishal21121** [comment]
pr merged #163
