### ISSUE TITLE
[PATTERN] Add star pattern in C, Pattern45

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#166]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![ray-so-export](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/1c89b6c3-1559-4bbc-9407-45c97c9b4f78)

### Filename

Pattern45.c

**Comment by AtharvePandey** [comment]
can you assign this to me please? i can do it

**Comment by Vishal21121** [comment]
ok, @AtharvePandey you can work on this issue.
