### ISSUE TITLE
[PATTERN] Add star pattern in JavaScript, Pattern45

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#167]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![ray-so-export](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/bd4bebc4-dff4-4143-bbe7-b1abec89b884)

### Filename

Pattern45.js

**Comment by abhishek09827** [comment]
hello pls assign this task to me

**Comment by Vishal21121** [comment]
@abhishek09827 someone already made pr and started working on it, so I can't assign you this task.

**Comment by ujju2000** [comment]
can i work on this issue ? if nobody is working on it.

**Comment by Vishal21121** [comment]
@ujju2000 you can work on this issue.

**Comment by Vishal21121** [comment]
pr merged #209
