### ISSUE TITLE
[PATTERN] Add star pattern in Java, Pattern47

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#168]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![ray-so-export (1)](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/2774134d-cef9-4fdc-a5f5-8302f8d03f79)

### Filename

Pattern47.java

**Comment by Sohini3018** [comment]
Please assign this issue to me.

**Comment by Vishal21121** [comment]
ok, @Sohini3018 you can work on this issue.
