### ISSUE TITLE
[PATTERN] Add star pattern in JavaScript, Pattern47

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#169]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![ray-so-export (1)](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/7ce5d548-d8b7-4067-91c5-37c4ebfd70ed)

### Filename

Pattern47.js

**Comment by AtharvePandey** [comment]
Hey can you assign this to me? i can do it

**Comment by Vishal21121** [comment]
@AtharvePandey you can work on this issue.

**Comment by shivam0277** [comment]
please assign me this issue , i want to work on this code

**Comment by Vishal21121** [comment]
@shivam0277 it's already assigned to @AtharvePandey

**Comment by Vishal21121** [comment]
pr merged #191
