### ISSUE TITLE
[PATTERN] Add number pattern in JavaScript, Pattern48

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#184]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![48](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/3bf661ba-0221-4983-a136-95ac22479a06)

### Filename

Pattern48.js

**Comment by OkelloSam21** [comment]
assign this to me.

**Comment by shivam0277** [comment]
i would like to work on  this issue please assign this to me.
