### ISSUE TITLE
[PATTERN] Add number pattern in Java, Pattern48

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#185]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![48](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/77371f7a-843d-463a-89ad-609cc9d78d1c)

### Filename

Pattern48.java

**Comment by OkelloSam21** [comment]
can I work on this?

**Comment by OkelloSam21** [comment]
Consider this as a work done.

![pattern48](https://github.com/Vishal21121/Patterns-different-language/assets/115361239/9e060e48-1c31-4b47-8846-b249164dbb81)

waiting for assignment then I create my pr

**Comment by Vishal21121** [comment]
ok, @OkelloSam21 you can work on this issue.
