### ISSUE TITLE
[PATTERN] Add number pattern in C, Pattern48

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#187]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![48](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/89a12fa4-18a8-43e7-a0b7-d052efc2e355)

### Filename

Pattern48.c

**Comment by Notand105** [comment]
Hi !, I think I can solve this one.
