### ISSUE TITLE
Add X star pattern in JavaScript

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#19]
# Description

## Task:
1. For the given input n the number of rows printed should be 2*n-1 for ex: 

![31](https://user-images.githubusercontent.com/89929777/235687067-82bc05df-bc6d-49d7-a3c0-c702d9853e2e.png)

## Note
> filename should be `Pattern31.js`

**Comment by Vishal21121** [comment]
Hey @bishalbera yes, you can work on this issue.

**Comment by bishalbera** [comment]
@Vishal21121 hey when I'm trying to create a file named Pattern31.js its showing that it already exists

**Comment by Vishal21121** [comment]
Sorry @bishalbera for this inconvenience the Javascript code for this problem was already added. So I will close this issue and I am going to raise an issue for another pattern you can contribute to that.

**Comment by bishalbera** [comment]
ok sure
