### ISSUE TITLE
[PATTERN] Add Pyramid of Prime Numbers pattern in Java, Pattern49

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#193]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![49](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/374e33f2-d58a-4368-977f-2e8a2ddb3822)

### Filename

Pattern49.java

**Comment by Abhinavagarwa** [comment]
Hey there 
Please this to me

**Comment by Vishal21121** [comment]
ok, @Abhinavagarwa you can work on this issue.

**Comment by Vishal21121** [comment]
pr merged #199
