### ISSUE TITLE
[PATTERN] Add Pyramid of Prime Numbers pattern in C, Pattern49

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#195]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![49](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/8ad946f4-5ce1-40f9-8edf-cb05a207a8ea)

### Filename

Pattern49.c

**Comment by metflekx** [comment]
// Assuming there is a function isPrime(), that returns true( 1 in terms of C ) when ever passed a prime integer as arg. 

void printLineOfPrimes(int offset, int lineDigits, int max) {
// offset is the value, that this recursive call begin from ( eg : for the second line offset = 3 )
// recursively calls itself, each time increments the lineDigit
    if (lineDigits >= max) { // base case
        return;
    }
    
    int primesInThisLine = 0;

    while (primesInThisLine < lineDigits) { 
        if (isPrime(offset)) {
            printf("%d ", offset);
            primesInThisLine++;
        }
        
        offset++;
    }
    
    printf("\n"); // print a line
    printLineOfPrimes(offset, ++lineDigits, max);
}

int main() {
    int n = 5;
    
    printLineOfPrimes(1, 1, n); // call the function with this initial values
    
    return 0;
}

**Comment by Vishal21121** [comment]
@metflekx do you want to work on this issue?

**Comment by metflekx** [comment]
sure

**Comment by Vishal21121** [comment]
pr merged #196
