### ISSUE TITLE
[PATTERN] Add even number pattern in C, Pattern50

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#201]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![50](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/97a98e49-5a62-4f8c-8237-8a389f936023)

### Filename

Pattern50.c

**Comment by Abhinavagarwa** [comment]
Hey there please assign this to me

**Comment by Vishal21121** [comment]
pr merged #203
