### ISSUE TITLE
[PATTERN] Add even number pattern in Java, Pattern50

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#202]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![50](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/302d0d3e-0eb2-46b9-a2c3-b3854e24cbe2)

### Filename

Pattern50.java

**Comment by Abhinavagarwa** [comment]
Hey there please assign this to me

**Comment by SagarBawanthade** [comment]
Hey Please Assign this to me

**Comment by Vishal21121** [comment]
@SagarBawanthade you can work on this issue. @Abhinavagarwa I have assigned you the issue for C.

**Comment by SagarBawanthade** [comment]
Thanks that will be my first PR ;)
