### ISSUE TITLE
[PATTERN] Add even number pattern in Python, Pattern50

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#204]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![50](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/a92b9feb-60f1-4c74-858c-f61acf498e91)

### Filename

Pattern50.py

**Comment by Raafeh** [comment]
I don't understand, like can you explain that what is the exact output you are looking for when an input n is given?

**Comment by Vishal21121** [comment]
@Raafeh as I have mentioned above for n=5 the above pattern should print and for other inputs respective output should be printed.
