### ISSUE TITLE
Add star pattern in JavaScript

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#21]
# Description
## Task
1. For the given input n the number of rows printed should be 2*n-1 for ex:

![32](https://user-images.githubusercontent.com/89929777/236439646-b86ae645-a6ec-4db5-8396-eedff3918937.png)

## Note
> Filename should be Pattern32.js

**Comment by bishalbera** [comment]
@Vishal21121 hey then I'm starting to work on this issue

**Comment by Vishal21121** [comment]
ok, @bishalbera I am assigning this issue to you.

**Comment by bishalbera** [comment]
@Vishal21121 I've made a PR please review it.

**Comment by Vishal21121** [comment]
@bishalbera I reviewed your pr and the code was running correctly so I have merged it and thank you for your contribution.
