### ISSUE TITLE
[PATTERN] Add Pyramid of Prime Numbers pattern in bash, Pattern49

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#211]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![49](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/07fba09d-5d7a-45b2-9b41-d362856b78db)

### Filename

Pattern49.sh

**Comment by Phoenix1504e** [comment]
I would like to work on this

**Comment by sunny0625** [comment]
Hey @Vishal21121,
I would like to contribute to open-source.
Can you assign this issue to @sunny0625?

**Comment by Vishal21121** [comment]
ok, @sunny0625 you can work on this issue.
