### ISSUE TITLE
[PATTERN] Add right angled triangle of Alphabets in bash, Pattern28

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#215]
### Description

Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![28](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/3c0959e1-0aab-4f2d-a7ca-60e8a14a1490)

### Filename

Pattern28.sh

**Comment by vmantri83** [comment]
Please assign me this issue

**Comment by vishaldev21** [comment]
pr merged #216
