### ISSUE TITLE
Add star pattern in C

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#23]
# Description

## Task
1. For the given input n the number of rows printed should be 2*n-1 for ex:

![32](https://user-images.githubusercontent.com/89929777/236657157-0ef3fd8c-7519-4e87-bd06-9b020dc1f08d.png)

## Note
> Filename should be Pattern32.c

**Comment by bishalbera** [comment]
@Vishal21121 hey I would like to work on this can you assign this to me?

**Comment by Vishal21121** [comment]
ok, @bishalbera  you can work on this issue
