### ISSUE TITLE
Add plus pattern in Java

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#26]
# Description

## Task
1. For the given input n the number of rows printed should be 2*n-1 for ex:

![33](https://user-images.githubusercontent.com/89929777/236762590-e04bdcff-8a70-4ce3-be43-69483c131a51.png)

## Note
> Filename should be Pattern33.java

**Comment by bishalbera** [comment]
@Vishal21121 can you assign me this issue?

**Comment by Vishal21121** [comment]
ok
