### ISSUE TITLE
Add plus pattern in C, Pattern33

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#27]
# Description
## Task
1. For the given input n the number of rows printed should be 2*n-1 for ex:

![33](https://user-images.githubusercontent.com/89929777/236823147-04881985-8b71-486a-9a75-96287fd2340b.png)

## Note:
> Filename should be Pattern33.c

**Comment by Angreatguy01** [comment]
I'm working on it

**Comment by Vishal21121** [comment]
pr merged #29
