### ISSUE TITLE
Add plus pattern in Python, Pattern33

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#32]
# Description

## Task
1. For the given input n the number of rows printed should be 2*n-1 for ex:

![33](https://user-images.githubusercontent.com/89929777/236980475-366900fa-adeb-40c6-a5af-ae56fc914277.png)

## Note
> Filename should be Pattern33.py

**Comment by JayPankajPatel** [comment]
Just added

**Comment by Vishal21121** [comment]
@JayPankajPatel this issue is for Python and you have made pr for C.

**Comment by KPR111** [comment]
can you please assign it for me

**Comment by JayPankajPatel** [comment]
hey @Vishal21121 sorry about, please assign the next issue to me

**Comment by Vishal21121** [comment]
@JayPankajPatel check next issue which I will raise and ask to assign it to you before working on it.
