### ISSUE TITLE
Add plus pattern in JavaScript, Pattern33

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#34]
# Description

## Task
1. For the given input n the number of rows printed should be 2*n-1 for ex:

![33](https://user-images.githubusercontent.com/89929777/236982139-f5a5a0e7-3fc1-48cc-b65f-c7349a5a535a.png)

## Note
> Filename should be Pattern33.js

**Comment by KPR111** [comment]
I would like to contribute to this task, Can you please assign me the above task

**Comment by Vishal21121** [comment]
ok

**Comment by Vishal21121** [comment]
pr merged #35
