### ISSUE TITLE
Add hollow triangle pattern in Java, Pattern34

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#37]
# Description

## Task
For the given input n the number of rows printed should be 2*n-1 for ex:

![34](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/35cadd1b-6b6f-451d-a858-09fea37fbd5d)

## Note
> Filename should be Pattern34.java

**Comment by MrigankaGhosh** [comment]
I was hoping if you could assign this to me.

**Comment by Vishal21121** [comment]
ok @MrigankaGhosh you can work on this issue

**Comment by Vishal21121** [comment]
pr merged #53
