### ISSUE TITLE
Add hollow triangle pattern in C, Pattern34

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#38]
# Description

## Task
For the given input n the number of rows printed should be 2*n-1 for ex:

![34](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/8b53972e-f737-4fa3-b15a-355879b43f52)

## Note
> Filename should be Pattern34.c

**Comment by JayPankajPatel** [comment]
can you assign this to me?

**Comment by Vishal21121** [comment]
ok @JayPankajPatel you can work on this issue

**Comment by Vishal21121** [comment]
@JayPankajPatel are you working on this issue?

**Comment by MrigankaGhosh** [comment]
The code for this Pattern is ready. Assign me and I'll send a pr.

**Comment by Vishal21121** [comment]
ok, @MrigankaGhosh I am assigning this issue to you.

**Comment by MrigankaGhosh** [comment]
@Vishal21121 I  have already sent a pull request

**Comment by Vishal21121** [comment]
pr merged #57
