### ISSUE TITLE
Add star pattern in C, Pattern35

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#43]
# Description
## Task
For the given input n the number of rows printed should be n for ex:

![35](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/31ebb1c6-8c19-4a35-87bc-9e74abe6311c)

## Note
> Filename should be Pattern35.c

**Comment by tchitrakorn** [comment]
I'll take this issue! Can you assign it to me? Thank you!

**Comment by Vishal21121** [comment]
ok, @tchitrakorn I am assigning this issue to you

**Comment by Vishal21121** [comment]
pr merged #51
