### ISSUE TITLE
Add star pattern in Java, Pattern35

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#44]
# Description

## Task
For the given input n the number of rows printed should be n for ex:
![35](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/86cc0f4e-bef7-43b2-887b-e895175365cc)

## Note
> Filename should be Pattern35.java

**Comment by KunalBhardwaj136** [comment]
Can you assign this one to me

**Comment by Vishal21121** [comment]
ok, @KunalBhardwaj136 I am assigning this issue to you

**Comment by Vishal21121** [comment]
pr mergerd #47
