### ISSUE TITLE
Add star pattern in JavaScript, Pattern35

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#45]
# Description

## Task

For the given input n the number of rows printed should be n for ex:
![35](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/bd0ba6bd-63dc-44fc-9c63-4a5e768e700f)

## Note

> Filename should be Pattern35.js

**Comment by sushma1031** [comment]
I'd like to work on this one

**Comment by Vishal21121** [comment]
ok, @sushma1031 I am assigning this issue to you

**Comment by Vishal21121** [comment]
pr merged #48
