### ISSUE TITLE
Add star pattern in Python, Pattern35

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#46]
# Description
## Task
For the given input n the number of rows printed should be n for ex:

![35](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/c5f1a872-f9fd-4904-87ac-cda0203ec920)

## Note
> Filename should be Pattern35.py

**Comment by MirrorCraze** [comment]
Can I take this one?

Just asking, this is the n=5 case, right?

**Comment by Vishal21121** [comment]
@MirrorCraze you can work on this issue and the above image is for n=5 case
