### ISSUE TITLE
Add Swastik star pattern in Java, Pattern36

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#50]
# Description
## Task
For the given input 7 the following pattern should print:

![36](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/2f2d048a-b11a-44d9-b2bf-9dc4f5a7eba5)

## Note
> Filename should be Pattern36.java

**Comment by somesh29** [comment]
Can I pick this up?

**Comment by Vishal21121** [comment]
ok @somesh29 I am assigning this issue to you.

**Comment by MrigankaGhosh** [comment]
I have the code ready for this particular pattern. Assign me to the task and I'll send another pull request.

**Comment by Vishal21121** [comment]
@somesh29 are you working on this issue?

**Comment by MrigankaGhosh** [comment]
@Vishal21121 I have already sent a pull request

**Comment by Vishal21121** [comment]
pr merged #57
