### ISSUE TITLE
Add swastik pattern in python, pattern 36

### ISSUE THREAD

**Issue by Arsh2001deep** [Vishal21121/Patterns-different-language#55]
### Description

# Description 
Task
For the given input 7 the following pattern should print:

### Pattern Image

![5451d0aa-d673-47db-b2c5-6fa1586de44a](https://github.com/Vishal21121/Patterns-different-language/assets/86292576/d203a200-4c1d-45b3-bfe9-a88c7c1958bb)

### Filename

Pattern36.py

**Comment by Arsh2001deep** [comment]
Can you assign this to me?

**Comment by Vishal21121** [comment]
ok you can work on this issue

**Comment by Vishal21121** [comment]
pr merged #56
