### ISSUE TITLE
Add Swastik star pattern in C, Pattern36

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#58]
## Task
For the given input 7 the following pattern should print:

### Pattern Image

![36](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/b31e5199-4c7e-4e1a-aab6-6b92dac19419)

### Filename

Filename should be Pattern36.c

**Comment by Kruthardh11** [comment]
I think I can work on this.

**Comment by Vishal21121** [comment]
ok, @Kruthardh11 I am assigning this issue to you

**Comment by MrigankaGhosh** [comment]
Assign the task to me and I can send a pr @Vishal21121
