### ISSUE TITLE
[PATTERN] Add a star pattern in Java, Pattern37

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#60]
## Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![37](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/cd28ed35-2c25-49c5-9018-b6b4f815e99d)

### Filename

Pattern37.java

**Comment by MrigankaGhosh** [comment]
Assign the task to me and I can send a pr @Vishal21121

**Comment by Vishal21121** [comment]
pr merged #77
