### ISSUE TITLE
[PATTERN] Add a star pattern in JavaScript, Pattern37

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#62]
## Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![37](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/1c9e7286-ca45-4304-a3ad-6f685dce0b07)

### Filename

Pattern37.js

**Comment by ValentinGarciaIriart** [comment]
I'll leave the code in the branch I'll make.

**Comment by Vishal21121** [comment]
@ValentinGarciaIriart do you want to work on this issue?

**Comment by ValentinGarciaIriart** [comment]
I've done the code but it does not let me push it.

**Comment by Vishal21121** [comment]
@ValentinGarciaIriart you can check two things:
1. check the filename
2. bring all the changes in your local system before pushing Pattern37.py file to GitHub

**Comment by ValentinGarciaIriart** [comment]
Done.

**Comment by Vishal21121** [comment]
@ValentinGarciaIriart what issue were you facing before?

**Comment by Vishal21121** [comment]
pr merged #66
