### ISSUE TITLE
[PATTERN] Add a star pattern in JavaScript, Pattern38

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#70]
## Task:
for the given input n the following pattern should print (n=5 for the below pattern):

### Pattern Image

![38](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/628a5f59-19aa-46e9-bee2-6204f5c36f6c)

### Filename

Pattern38.js

**Comment by johnweslee** [comment]
Hi @Vishal21121, I would like to contribute to this issue. Can this be assigned to me??

**Comment by Vishal21121** [comment]
ok, @johnweslee you can work on this issue.

**Comment by johnweslee** [comment]
Hi @Vishal21121,
I have created a PR ( #73 ) for this issue. Kindly take a look when you have a chance.
