### ISSUE TITLE
[PATTERN] Add a arrow star pattern in JavaScript, Pattern39

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#79]
## Task
for the given input n the following pattern should print (n=5 for the below pattern) and here we have a total of 7 rows for n = 5 so the number of rows printed should vary accordingly for the given input.

### Pattern Image

![39](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/2f1ac7d4-d644-460b-93a4-c0a2b82af4d3)

### Filename

Pattern39.js

**Comment by abhishek09827** [comment]
Hello @Vishal21121 already solved this issue pls assign this to me

**Comment by Vishal21121** [comment]
pr merged #86
