### ISSUE TITLE
[PATTERN] Add a arrow star pattern in Python, Pattern39

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#80]
## Task
for the given input n the following pattern should print (n=5 for the below pattern) and here we have a total of 7 rows for n = 5 so the number of rows printed should vary accordingly for the given input.

### Pattern Image

![39](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/5db29464-2c4b-42d4-ba8d-4d5200baec60)

### Filename

Pattern39.py

**Comment by SantiagoEscalante** [comment]
I think i can do it. Assign it to me, please

**Comment by Vishal21121** [comment]
ok @SantiagoEscalante you can work on this issue.
