### ISSUE TITLE
[PATTERN] Add a Binary number pattern in C, Pattern40

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#89]
## Task
for the given input n the following pattern should print (n=5 for the below pattern)

### Pattern Image

![40](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/893052a9-c67d-4c6c-809c-7883165dd6e8)

### Filename

Pattern40.c

**Comment by livvyaaa** [comment]
@Vishal21121 done, will pr after assign

**Comment by Vishal21121** [comment]
ok @livvyaaa you can work on this issue
