### ISSUE TITLE
[PATTERN] Add a Binary number pattern in Java, Pattern40

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#90]
## Task
for the given input n the following pattern should print (n=5 for the below pattern)

### Pattern Image

![40](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/c845c4e4-c908-41ee-8585-fb9a0ce90182)

### Filename

Pattern40.java

**Comment by livvyaaa** [comment]
@Vishal21121 finished, will send pr after assign

**Comment by Vishal21121** [comment]
ok @livvyaaa you can work on this issue.
