### ISSUE TITLE
[PATTERN] Add a Binary number pattern in JavaScript, Pattern40

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#93]
## Task
for the given input n the following pattern should print (n=5 for the below pattern)

### Pattern Image

![40](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/fa27c5f3-5732-4f61-be85-4200a9785283)

### Filename

Pattern40.js

**Comment by abhishek09827** [comment]
I have solved this issue pls assign this to me

**Comment by Vishal21121** [comment]
ok, @abhishek09827 you can work on this issue.

**Comment by Vishal21121** [comment]
pr merged #99
