### ISSUE TITLE
[PATTERN] Add a Binary number pattern in Python, Pattern40

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#94]
## Task
for the given input n the following pattern should print (n=5 for the below pattern)

### Pattern Image

![40](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/1f816bb7-3b9c-4453-91dd-b3479575b5b4)

### Filename

Pattern40.py

**Comment by livvyaaa** [comment]
@Vishal21121 done
