### ISSUE TITLE
[PATTERN] Add a number pattern in Java, Pattern41

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#96]
## Task
for the given input n the following pattern should print (n=5 for the below pattern)

### Pattern Image

![41](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/a42fb2ed-9913-4285-a68f-b6650a5d76c8)

### Filename

Pattern41.java

**Comment by achhayapathak** [comment]
I would like to work upon this

**Comment by Vishal21121** [comment]
Ok @achhayapathak you can work on this issue.

**Comment by achhayapathak** [comment]
Made the pattern, merge the pull request!

**Comment by livvyaaa** [comment]
you might want to consider separating the files into different folders with one for each lang
