### ISSUE TITLE
[PATTERN] Add a number pattern in JavaScript, Pattern41

### ISSUE THREAD

**Issue by Vishal21121** [Vishal21121/Patterns-different-language#97]
## Task
for the given input n the following pattern should print (n=5 for the below pattern)

### Pattern Image

![41](https://github.com/Vishal21121/Patterns-different-language/assets/89929777/d76d8c32-7195-41e4-a30a-6a8886e4464c)

### Filename

Pattern41.js

**Comment by achhayapathak** [comment]
Let me complete this as well!

**Comment by achhayapathak** [comment]
I haven't used javascript before, can you help me with this error?
<img width="1440" alt="image" src="https://github.com/Vishal21121/Patterns-different-language/assets/93811742/a21477b6-5217-4597-9fdc-32dd5050cca5">

**Comment by Vishal21121** [comment]
@achhayapathak error is in the 34th line you are passing variable j which is holding integer, pass it as string then it will run.

**Comment by achhayapathak** [comment]
Done. Made the required changes, you may merge both the commits

**Comment by Vishal21121** [comment]
pr merged #103
